version: '3.1'

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - 8086:8086
            - 2003:2003
        environment:
            INFLUXDB_GRAPHITE_ENABLED: "true"
            INFLUXDB_ADMIN_USER: "admin"
            INFLUXDB_ADMIN_PASSWORD: "admin123"
            INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
        volumes:
            - /var/lib/influxdb:/var/lib/influxdb
            - /etc/influxdb:/etc/influxdb
    grafana-influxdb-sample:
        image: resulguldibi/grafana-influxdb-sample
        container_name: grafana-influxdb-sample
        restart: always        
    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            GF_SECURITY_ADMIN_PASSWORD: "admin"
            GF_SECURITY_ADMIN_USER: "admin"
        depends_on:
            - influxdb
        links:
            - influxdb
        restart: always
        ports:
            - 3000:3000

